### ISSUE TITLE
agency relations/tables are not created until first write

### ISSUE THREAD

**Issue by jaimeventura** [CityOfLosAngeles/mds-core#265]
When running a clean install i noticed that agency relations/tables are not created until first write.

1) i try to get the existing vehicles (should return an empty list)
`[me@devbox mds-core]$ curl 127.0.0.1:8099/agency/vehicles -H "Content-Type: application/json" -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm92aWRlcl9pZCI6IjI0MTFkMzk1LTA0ZjItNDdjOS1hYjY2LWQwOWU5ZTNjMzI1MSIsImV4cCI6MjUyNDYwODAwMH0.XUl4kS-xJuXHRlwNA_--9CeM2TlTyepVgVU3ndKCvJo'
{"error":"server_error","error_description":"Unknown server error"}
`
Logs from agency component:
`"getVehicles fail" "error: relation \"devices\" does not exist"`

2) i do a write(no error):
`[me@devbox mds-core]$ curl -d @test_p2_add_vehicle.json -X POST 127.0.0.1:8099/agency/vehicles -H "Content-Type: application/json" -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm92aWRlcl9pZCI6IjI0MTFkMzk1LTA0ZjItNDdjOS1hYjY2LWQwOWU5ZTNjMzI1MSIsImV4cCI6MjUyNDYwODAwMH0.XUl4kS-xJuXHRlwNA_--9CeM2TlTyepVgVU3ndKCvJo'
{}
`

3) i try to get the existing vehicles (and works!):
`[me@devbox mds-core]$ curl 127.0.0.1:8099/agency/vehicles -H "Content-Type: application/json" -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm92aWRlcl9pZCI6IjI0MTFkMzk1LTA0ZjItNDdjOS1hYjY2LWQwOWU5ZTNjMzI1MSIsImV4cCI6MjUyNDYwODAwMH0.XUl4kS-xJuXHRlwNA_--9CeM2TlTyepVgVU3ndKCvJo'
{"total":1,"links":{"first":"http://agency:4000/agency/vehicles?skip=0&take=1000","last...}
`

Not sure if this is a bug or a feature.

**Comment by macsj200** [comment]
I believe this is intended behavior. I recommend constructing a script that inserts a small record into the table when you initialize if this is causing issues.

The reason this happens is because the client only runs the initialization logic when you issue a write request rather than doing this sort of check on startup.

**Comment by avatarneil** [comment]
This isn't _exactly_ intended, but it is known behavior. Due to there being two separate db connections (R & R/W), and the connections being lazily initialized in `mds-db`, you can have a read occur before `mds-db` has kicked off the initial migration (which occurs upon a writeable connection being established). This is a known issue, and while it hasn't been fixed here yet, the [fork E&A maintains](https://github.com/lacuna-tech/mds-core) has switched over to using TypeORM managed tables, which resolves this issue.

**Comment by jaimeventura** [comment]
@avatarneil  Sorry to ask. What's this "fork E&A maintains"? is it a dev/unstable version? 
If not, should i use it instead?
Also, I had a quick look at the E&A repo. Looks like issue raising is disabled. Should i still use this repo for raising then?

I believe this issue may be closed.
Thanks.

**Comment by avatarneil** [comment]
Hi @jaimeventura, the “fork that E&A maintains” could be looked at as a dev/unstable version, but it is considered stable on our end. It was cut due to the E&A team needing a more agile repo, as we have CI/CD configured for publishing build artifacts upon merges to branches like `develop` (called `dev` in this version of the repo, another inconsistency), and there are times that we need to release changes without waiting for someone from the OMF who has approval access on this repository to approve changes. For a while, we attempted to keep this repo in sync with updates on the E&A fork, but it became increasingly onerous, so the E&A fork is now more of a “hard fork”.

**Comment by jaimeventura** [comment]
@avatarneil thanks for the reply.
We'll use it then and keep you posted on any issue we find.
